// <auto-generated />
using System;
using ControleFinanceiro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleFinanceiro.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiro.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1c6a98a-5ff2-4d1e-a158-be2861fde84b"),
                            Data = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cartão de Crédito",
                            Tipo = 0,
                            Valor = 825.82m
                        },
                        new
                        {
                            Id = new Guid("c9b5d3c3-6e1f-4f3e-9d5b-f9d5c5d5c5d5"),
                            Data = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Curso C#",
                            Tipo = 0,
                            Valor = 200.00m
                        },
                        new
                        {
                            Id = new Guid("d8b5d3c3-7e1f-4f3e-9d5b-f9d5c5d5c5d6"),
                            Data = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Salário",
                            Tipo = 1,
                            Valor = 7000.00m
                        },
                        new
                        {
                            Id = new Guid("e8b5d3c3-8e1f-4f3e-9d5b-f9d5c5d5c5d7"),
                            Data = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mercado",
                            Tipo = 0,
                            Valor = 3000.00m
                        },
                        new
                        {
                            Id = new Guid("f8b5d3c3-9e1f-4f3e-9d5b-f9d5c5d5c5d8"),
                            Data = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Farmácia",
                            Tipo = 0,
                            Valor = 300.00m
                        },
                        new
                        {
                            Id = new Guid("08b5d3c3-ae1f-4f3e-9d5b-f9d5c5d5c5d9"),
                            Data = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Combustível",
                            Tipo = 0,
                            Valor = 800.25m
                        },
                        new
                        {
                            Id = new Guid("18b5d3c3-be1f-4f3e-9d5b-f9d5c5d5c5da"),
                            Data = new DateTime(2022, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Financiamento Carro",
                            Tipo = 0,
                            Valor = 900.00m
                        },
                        new
                        {
                            Id = new Guid("28b5d3c3-ce1f-4f3e-9d5b-f9d5c5d5c5db"),
                            Data = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Financiamento Casa",
                            Tipo = 0,
                            Valor = 1200.00m
                        },
                        new
                        {
                            Id = new Guid("38b5d3c3-de1f-4f3e-9d5b-f9d5c5d5c5dc"),
                            Data = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Freelance Projeto XPTO",
                            Tipo = 1,
                            Valor = 2500.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
